FROM nvidia/cuda:11.2.1-runtime-ubuntu20.04


RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get update && \
    apt install -y --no-install-recommends python3-pip python3
RUN apt-get install  -y postgresql sudo
# Set container working directory
WORKDIR /api

# Copy api files
COPY ./api/* /api/

# Install requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt
RUN systemctl enable postgresql.service
RUN service postgresql start; sudo -u postgres psql < /api/createdatabase.sql
RUN echo "listen_addresses = '*'" >> /etc/postgresql/12/main/postgresql.conf 
RUN echo "host    all     	all     0.0.0.0/0       md5" >> /etc/postgresql/12/main/pg_hba.conf

# Copy all user files
COPY ./info.py /api/info.py
COPY ./sentiment.py /api/sentiment.py
COPY ./conversation.py /api/conversation.py
COPY ./robot.py /api/robot.py
COPY ./color.py /api/color.py
COPY ./comment.py /api/comment.py
COPY ./human.py /api/human.py
COPY ./DatabaseFactory.py /api/DatabaseFactory.py
RUN python <<EOF
from comment import Comment
from sentiment import SentimentScore,Sentiment
Comment("Alec","BallsTEST",SentimentScore("neutral",0.14353797,0.14353797,0.14353797)).save()
EOF
# Entry point to start unvicorn server
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
CMD ["bash", "-c", "service postgresql start;uvicorn main:app --host 0.0.0.0 --port 80"]

